spring.application.name=produto-service
spring.datasource.url=jdbc:mysql://localhost:3306/produto?createDatabaseIfNotExist=true
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
