spring.application.name=gateway-serve

eureka.client.service-url.defaultZone=http://eureka-serve:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.gateway.server.webflux.routes[0].id=produtos
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUTO-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/produtos/**


spring.cloud.gateway.server.webflux.routes[1].id= order
spring.cloud.gateway.server.webflux.routes[1].uri=lb://oder-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/order/**


server.port=8080

